alias c='code .'
alias gs='git status'
alias gb='git branch'
alias gcb='git checkout -b'
alias gc='git checkout'
alias ga='git add'
alias gom='git commit -m'
alias justmaster='git branch | grep -v "master" | xargs git branch -D'
